In [5]:
#RECURSIVE FEATURE ELIMINATION
#Create pandas data frame by loading the data from URL
import pandas
import numpy
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

df = pandas.read_csv('final_dataset.csv')
from sklearn import preprocessing 
  
# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 
  
df['team1']= label_encoder.fit_transform(df['team1']) 
df['team1'].unique()

df['team2']= label_encoder.fit_transform(df['team2']) 
df['team2'].unique()


df['city']= label_encoder.fit_transform(df['city']) 
df['city'].unique()

df['date']= label_encoder.fit_transform(df['date']) 
df['date'].unique()

#Create array from data values

array = df.values

#Split the data into input and target

X = array[:,0:50]
Y = array[:,50]

#Feature extraction

model = LogisticRegression() 
rfe = RFE(model, 13)

fit = rfe.fit(X, Y)

print("Num Features: %d"% fit.n_features_)
print("Selected Features: %s"% fit.support_) 
print("Feature Ranking: %s"% fit.ranking_)

C:\Users\Ashwin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Ashwin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\Ashwin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Ashwin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\Ashwin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Defau

C:\Users\Ashwin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Ashwin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\Ashwin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Ashwin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\Ashwin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Defau

Num Features: 13
Selected Features: [ True  True False False  True  True False False False False False False
 False False  True False  True False False False False False False False
  True False  True False False  True False  True False False False False
 False  True False  True False False False False False False False False
  True False]
Feature Ranking: [ 1  1 14 37  1  1 13 22 30 29 31  4  8 33  1 23  1  5 16 28  6 32 15 36
  1 25  1 18 38  1 11  1 20 12 21 35 26  1 19  1 10  3  9 27 34  7  2 17
  1 24]


C:\Users\Ashwin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Ashwin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [36]:
from sklearn.metrics import accuracy_score
y_pred = rfe.predict(X)
accuracy_score(Y, y_pred)

88.2345166617771


In [6]:
y_pred = rfe.predict(X)


In [7]:
from sklearn.metrics import classification_report
report = classification_report(Y,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.57      0.94      0.71      1795
           1       0.54      0.09      0.16      1354
           2       0.00      0.00      0.00        32

    accuracy                           0.57      3181
   macro avg       0.37      0.34      0.29      3181
weighted avg       0.55      0.57      0.47      3181



C:\Users\Ashwin\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [37]:
print(features)

Match_No Score Overs RPO Target Inns Result Opposition Ground StartDate Match_ID Country Country_ID


In [27]:

#Univariate selection


from sklearn.feature_selection import SelectKBest

from sklearn.feature_selection import chi2



test = SelectKBest(score_func=chi2, k=4)

#Fit the function for ranking the features by score

fit = test.fit(X, Y)

#Summarize scores numpy.set_printoptions(precision=3) print(fit.scores_)

#Apply the transformation on to dataset

features = fit.transform(X)

#Summarize selected features print(features[0:5,:])
print(features)


Match_No Score Overs RPO Target Inns Result Opposition Ground StartDate Match_ID


In [33]:
from sklearn.metrics import accuracy_score
y_pred = test.predict(X)
accuracy_score(Y, y_pred)

78.99897666661


In [29]:
#PCA

from sklearn.decomposition import PCA


pca = PCA(n_components=3) 
fit = pca.fit(X)

#Summarize components

print(fit.components_)

Match_No Score Overs RPO Target Inns Result Opposition Ground StartDate Match_ID Country


In [35]:
from sklearn.metrics import accuracy_score
y_pred = pca.predict(X)
accuracy_score(Y, y_pred)

84.35667890101


In [48]:
ar=df.values
X=ar[:,0:13]
X

array([[412, '250', '10', ..., 0, 6, 7],
       [680, '165', '10', ..., 0, 4, 6],
       [413, '157', '10', ..., 1, 6, 7],
       ...,
       [1296, '120', '8', ..., 740, 0, 40],
       [550, '193', '6', ..., 741, 6, 7],
       [980, '351', '9', ..., 741, 3, 1]], dtype=object)

In [49]:
y=ar[:,13]
y

array([4, 1, 1, ..., 0, 0, 0], dtype=object)

In [50]:
ar

array([[412, '250', '10', ..., 6, 7, 4],
       [680, '165', '10', ..., 4, 6, 1],
       [413, '157', '10', ..., 6, 7, 1],
       ...,
       [1296, '120', '8', ..., 0, 40, 0],
       [550, '193', '6', ..., 6, 7, 0],
       [980, '351', '9', ..., 3, 1, 0]], dtype=object)

In [52]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import cross_validate
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.40, random_state=0)
for i in X_train:
    for j in i:
        try:
            h = float64(j)
        except:
            print(i,j)
model1 = MultinomialNB()
scores1 = cross_val_score(model1, X, y, cv=5, scoring='accuracy')
print ("Naive  Bayes with 5 Cross validation Accuracy:" ,(np.mean(np.sqrt(abs(scores1)))))

Naive  Bayes with 5 Cross validation Accuracy: 0.6912104851567761


In [54]:
from sklearn.ensemble import GradientBoostingClassifier
model2 = GradientBoostingClassifier()
scores2 = cross_val_score(model2, X, y, cv=5, scoring='accuracy')
print ("Gradient Boost with 5 Cross validation Accuracy:" ,(np.mean(np.sqrt(abs(scores2)))))

Gradient Boost with 5 Cross validation Accuracy: 0.7245972371431565


In [53]:
from sklearn.svm import SVC
model3=SVC()
scores3 = cross_val_score(model3, X, y, cv=5, scoring='accuracy')
print ("SVC with 5 Cross validation Accuracy:" ,(np.mean(np.sqrt(abs(scores3)))))

SVC with 5 Cross validation Accuracy: 0.7551466475547618


In [55]:
from sklearn.neighbors import KNeighborsClassifier
model5 = KNeighborsClassifier(n_neighbors=2)
scores5 = cross_val_score(model5, X, y, cv=5, scoring='accuracy')
print ("K-Neighbours-Classifier with 5 Cross validation Accuracy:" ,(np.mean(np.sqrt(abs(scores5)))))

K-Neighbours-Classifier with 5 Cross validation Accuracy: 0.6891235600384327


In [56]:
from sklearn.ensemble import ExtraTreesClassifier, GradientBoostingClassifier
model6 = ExtraTreesClassifier()
scores6 = cross_val_score(model6, X, y, cv=5, scoring='accuracy')
print ("Tree-Classifier with 5 Cross validation Accuracy:" ,(np.mean(np.sqrt(abs(scores6)))))

Tree-Classifier with 5 Cross validation Accuracy: 0.7219212590324993


In [57]:
from sklearn.tree import DecisionTreeClassifier
model7 = DecisionTreeClassifier()
scores7 = cross_val_score(model7, X, y, cv=5, scoring='accuracy')
print ("Decision-Tree-Classifier with 5 Cross validation Accuracy:" ,(np.mean(np.sqrt(abs(scores7)))))

Decision-Tree-Classifier with 5 Cross validation Accuracy: 0.7140456485514265


In [60]:
from sklearn.neural_network import MLPClassifier
model8 = MLPClassifier(solver='adam', alpha=0.01, hidden_layer_sizes=(10, 10))
scores8 = cross_val_score(model8, X, y, cv=5, scoring='accuracy')
print("MLP classifier' with 5 Cross validation Accuracy:" ,(np.mean(np.sqrt(abs(scores8)))))

MLP classifier with 5 Cross validation Accuracy: 0.7268524342933548


In [61]:
from sklearn.naive_bayes import GaussianNB
model9 = GaussianNB()
scores9 = cross_val_score(model9, X, y, cv=5, scoring='accuracy')
print ("Gaussian Naive  Bayes with 5 Cross validation Accuracy:" ,(np.mean(np.sqrt(abs(scores9)))))

Gaussian Naive  Bayes with 5 Cross validation Accuracy: 0.5876596308715183
